---

- hosts: all
  become: true
  tasks: 

  - name: update repo
    yum:
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install httpd
    yum:
      name: httpd
    when: ansible_distribution == "RedHat"

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]
