---

- hosts: all
  become: true
  tasks: 

  - name: update repo
    yum:
      update_cache: yes
    

  - name: install httpd
    yum:
      name: httpd
   

  - name: update repository index
    apt:
      update_cache: yes
    
